var tarotCards = [
        {name: 'Ace of Cups', class: 'aceCups', img: 'images/cards/aceOfCups.jpg', def: 'House of the true heart, joy, content, abode, nourishment, abundance, fertility; Inflexible will, unalterable law.'},
        {name: 'Two of Cups', class: 'twoCups', img: 'images/cards/twoOfCups.jpg', def: 'Love, passion, friendship, affinity, union, concord, sympathy, the interrelation of the sexes, and--as a suggestion apart from all offices of divination--that desire which is not in Nature, but by which Nature is sanctified. Favourable in things of pleasure and business, as well as love; also wealth and honour.'},
        {name: 'Three of Cups', class: 'threeCups', img: 'images/cards/threeOfCups.jpg', def: 'The conclusion of any matter in plenty, perfection and merriment; happy issue, victory, fulfilment, solace, healing. Unexpected advancement for a military man.'},
        {name: 'Four of Cups', class: 'fourCups', img: 'images/cards/fourOfCups.jpg', def: 'Weariness, disgust, aversion, imaginary vexations, as if the wine of this world had caused satiety only; another wine, as if a fairy gift, is now offered the wastrel, but he sees no consolation therein. This is also a card of blended pleasure. Contrarieties.'},
        {name: 'Five of Cups', class: 'fiveCups', img: 'images/cards/fiveOfCups.jpg', def: 'It is a card of loss, but something remains over; three have been taken, but two are left; it is a card of inheritance, patrimony, transmission, but not corresponding to expectations; with some interpreters it is a card of marriage, but not without bitterness or frustration. Generally favourable; a happy marriage; also patrimony, legacies, gifts, success in enterprise.'},
        {name: 'Six of Cups', class: 'sixCups', img: 'images/cards/sixOfCups.jpg', def: 'A card of the past and of memories, looking back, as--for example--on childhood; happiness, enjoyment, but coming rather from the past; things that have vanished. Another reading reverses this, giving new relations, new knowledge, new environment, and then the children are disporting in an unfamiliar precinct.'},
        {name: 'Seven of Cups', class: 'sevenCups', img: 'images/cards/sevenOfCups.jpg', def: 'Fairy favours, images of reflection, sentiment, imagination, things seen in the glass of contemplation; some attainment in these degrees, but nothing permanent or substantial is suggested. Fair child; idea, design, resolve, movement.'},
        {name: 'Eight of Cups', class: 'eightCups', img: 'images/cards/eightOfCups.jpg', def: 'Giving joy, mildness, timidity, honour, modesty. In practice, it is usually found that the card shows the decline of a matter, or that a matter which has been thought to be important is really of slight consequence--either for good or evil. Can also mean marriage with a fair woman.'},
        {name: 'Nine of Cups', class: 'nineCups', img: 'images/cards/nineOfCups.jpg', def: 'Concord, contentment, physical bien-être; also victory, success, advantage; satisfaction for the Querent or person for whom the consultation is made. Of good augury for military men.'},
        {name: 'Ten of Cups', class: 'tenCups', img: 'images/cards/tenOfCups.jpg', def: 'Concord, contentment, physical bien-être; also victory, success, advantage; satisfaction for the Querent or person for whom the consultation is made. Of good augury for military men.'},
        {name: 'Page of Cups', class: 'pageCups', img: 'images/cards/pageOfCups.jpg', def: 'Fair young man, one impelled to render service and with whom the Querent will be connected; a studious youth; news, message; application, reflection, meditation; also these things directed to business. Good augury; also a young man who is unfortunate in love.'},
        {name: 'Knight of Cups', class: 'knightCups', img: 'images/cards/knightOfCups.jpg', def: 'Arrival, approach--sometimes that of a messenger; advances, proposition, demeanour, invitation, incitement. A visit from a friend, who will bring unexpected money to the Querent.'},
        {name: 'Queen of Cups', class: 'queenCups', img: 'images/cards/queenOfCups.jpg', def: 'Good, fair woman; honest, devoted woman, who will do service to the Querent; loving intelligence, and hence the gift of vision; success, happiness, pleasure; also wisdom, virtue; a perfect spouse and a good mother.'},
        {name: 'King of Cups', class: 'kingCups', img: 'images/cards/kingOfCups.jpg', def: 'Fair man, man of business, law, or divinity; responsible, disposed to oblige the Querent; also equity, art and science, including those who profess science, law and art; creative intelligence. Beware of ill-will on the part of a man of position, and of hypocrisy pretending to help.'},
        {name: 'Ace of Pentacles', class: 'acePentacles', img: 'images/cards/aceOfPentacles.jpg', def: 'Perfect contentment, felicity, ecstasy; also speedy intelligence; gold. The most favorable of all cards.'},
        {name: 'Two of Pentacles', class: 'twoPentacles', img: 'images/cards/twoOfPentacles.jpg', def: 'On the one hand it is represented as a card of gaiety, recreation and its connexions, which is the subject of the design; but it is read also as news and messages in writing, as obstacles, agitation, trouble, embroilment. Troubles are more imaginary than real.'},
        {name: 'Three of Pentacles', class: 'threePentacles', img: 'images/cards/threeOfPentacles.jpg', def: 'Métier, trade, skilled labour; usually, however, regarded as a card of nobility, aristocracy, renown, glory. If for a man, celebrity for his eldest son.'},
        {name: 'Four of Pentacles', class: 'fourPentacles', img: 'images/cards/fourOfPentacles.jpg', def: 'The surety of possessions, cleaving to that which one has, gift, legacy, inheritance. For a bachelor, pleasant news from a lady'},
        {name: 'Five of Pentacles', class: 'fivePentacles', img: 'images/cards/fiveOfPentacles.jpg', def: 'The card foretells material trouble above all, whether in the form illustrated--that is, destitution--or otherwise. For some, it is a card of love and lovers-wife, husband, friend, mistress; also concordance, affinities. These alternatives cannot be harmonized. Conquest of fortune by reason.'},
        {name: 'Six of Pentacles', class: 'sixPentacles', img: 'images/cards/sixOfPentacles.jpg', def: 'Presents, gifts, gratification another account says attention, vigilance now is the accepted time, present prosperity, etc. The present must not be relied on.'},
        {name: 'Seven of Pentacles', class: 'sevenPentacles', img: 'images/cards/sevenOfPentacles.jpg', def: 'These are exceedingly contradictory; in the main, it is a card of money, business, barter; but one reading gives altercation, quarrels--and another innocence, ingenuity, purgation.Improved position for a lady\'s future husband.'},
        {name: 'Eight of Pentacles', class: 'eightPentacles', img: 'images/cards/eightOfPentacles.jpg', def: 'Work, employment, commission, craftsmanship, skill in craft and business, perhaps in the preparatory stage. A young man in business who has relations with the Querent; a dark girl.'},
        {name: 'Nine of Pentacles', class: 'ninePentacles', img: 'images/cards/nineOfPentacles.jpg', def: 'Prudence, safety, success, accomplishment, certitude, discernment. Prompt fulfilment of what is presaged by neighbouring cards.'},
        {name: 'Ten of Pentacles', class: 'tenPentacles', img: 'images/cards/tenOfPentacles.jpg', def: 'Gain, riches; family matters, archives, extraction, the abode of a family. Represents house or dwelling, and derives its value from other cards.'},
        {name: 'Page of Pentacles', class: 'pagePentacles', img: 'images/cards/pageOfPentacles.jpg', def: 'Application, study, scholarship, reflection; another reading says news, messages and the bringer thereof; also rule, management. A dark youth; a young officer or soldier; a child.'},
        {name: 'Knight of Pentacles', class: 'knightPentacles', img: 'images/cards/knightOfPentacles.jpg', def: 'Utility, serviceableness, interest, responsibility, rectitude-all on the normal and external plane. A useful man; useful discoveries.'},
        {name: 'Queen of Pentacles', class: 'queenPentacles', img: 'images/cards/queenOfPentacles.jpg', def: 'Opulence, generosity, magnificence, security, liberty. Dark woman; presents from a rich relative; rich and happy marriage for a young man.'},
        {name: 'King of Pentacles', class: 'kingPentacles', img: 'images/cards/kingOfPentacles.jpg', def: 'Valour, realizing intelligence, business and normal intellectual aptitude, sometimes mathematical gifts and attainments of this kind; success in these paths.'},
        {name: 'Ace of Swords', class: 'aceSwords', img: 'images/cards/aceOfSwords.jpg', def: 'Triumph, the excessive degree in everything, conquest, triumph of force. It is a card of great force, in love as well as in hatred. The crown may carry a much higher significance than comes usually within the sphere of fortune-telling. Great prosperity or great misery.'},
        {name: 'Two of Swords', class: 'twoSwords', img: 'images/cards/twoOfSwords.jpg', def: 'Conformity and the equipoise which it suggests, courage, friendship, concord in a state of arms; another reading gives tenderness, affection, intimacy. The suggestion of harmony and other favourable readings must be considered in a qualified manner, as Swords generally are not symbolical of beneficent forces in human affairs. Gifts for a lady, influential protection for a man in search of help.'},
        {name: 'Three of Swords', class: 'threeSwords', img: 'images/cards/threeOfSwords.jpg', def: 'Removal, absence, delay, division, rupture, dispersion, and all that the design signifies naturally, being too simple and obvious to call for specific enumeration. For a woman, the flight of her lover.'},
        {name: 'Four of Swords', class: 'fourSwords', img: 'images/cards/fourOfSwords.jpg', def: 'Vigilance, retreat, solitude, hermit\'s repose, exile, tomb and coffin. It is these last that have suggested the design. A bad card, but if reversed a qualified success may be expected by wise administration of affairs.'},
        {name: 'Five of Swords', class: 'fiveSwords', img: 'images/cards/fiveOfSwords.jpg', def: 'Degradation, destruction, revocation, infamy, dishonour, loss, with the variants and analogues of these. An attack on the fortune of the Querent'},
        {name: 'Six of Swords', class: 'sixSwords', img: 'images/cards/sixOfSwords.jpg', def: 'Journey by water, route, way, envoy, commissionary, expedient. The voyage will be pleasant.'},
        {name: 'Seven of Swords', class: 'sevenSwords', img: 'images/cards/sevenOfSwords.jpg', def: 'Design, attempt, wish, hope, confidence; also quarrelling, a plan that may fail, annoyance. The design is uncertain in its import, because the significations are widely at variance with each other. Dark girl; a good card; it promises a country life after a competence has been secured.'},
        {name: 'Eight of Swords', class: 'eightSwords', img: 'images/cards/eightOfSwords.jpg', def: 'Design, attempt, wish, hope, confidence; also quarrelling, a plan that may fail, annoyance. The design is uncertain in its import, because the significations are widely at variance with each other. Dark girl; a good card; it promises a country life after a competence has been secured.'},
        {name: 'Nine of Swords', class: 'nineSwords', img: 'images/cards/nineOfSwords.jpg', def: 'Death, failure, miscarriage, delay, deception, disappointment, despair. An ecclesiastic, a priest; generally, a card of bad omen.'},
        {name: 'Ten of Swords', class: 'tenSwords', img: 'images/cards/tenSwords.jpg', def: 'Whatsoever is intimated by the design; also pain, affliction, tears, sadness, desolation. It is not especially a card of violent death. Followed by Ace and King, imprisonment; for girl or wife, treason on the part of friends.'},
        {name: 'Page of Swords', class: 'pageSwords', img: 'images/cards/pageOfSwords.jpg', def: 'Authority, overseeing, secret service, vigilance, spying, examination, and the qualities thereto belonging. An indiscreet person will pry into the Querent\'s secrets.'},
        {name: 'Knight of Swords', class: 'knightSwords', img: 'images/cards/knightOfSwords.jpg', def: 'Skill, bravery, capacity, defence, address, enmity, wrath, war, destruction, opposition, resistance, ruin. There is therefore a sense in which the card signifies death, but it carries this meaning only in its proximity to other cards of fatality. A soldier, man of arms, satellite, stipendiary; heroic action predicted for soldier.'},
        {name: 'Queen of Swords', class: 'queenSwords', img: 'images/cards/queenOfSwords.jpg', def: 'Widowhood, female sadness and embarrassment, absence, sterility, mourning, privation, separation.'},
        {name: 'King of Swords', class: 'kingSwords', img: 'images/cards/kingOfSwords.jpg', def: 'Whatsoever arises out of the idea of judgment and all its connexions-power, command, authority, militant intelligence, law, offices of the crown, and so forth. A lawyer, senator, doctor.'},
        {name: 'Ace of Wands', class: 'aceWands', img: 'images/cards/aceOfWands.jpg', def: 'Fall, decadence, ruin, perdition, to perish also a certain clouded joy.Calamities of all kinds.'},
        {name: 'Two of Wands', class: 'twoWands', img: 'images/cards/twoOfWands.jpg', def: 'On the one hand, riches, fortune, magnificence; on the other, physical suffering, disease, chagrin, sadness, mortification. Surprise, wonder, enchantment, emotion, trouble, fear.'},
        {name: 'Three of Wands', class: 'threeWands', img: 'images/cards/threeOfWands.jpg', def: 'He symbolizes established strength, enterprise, effort, trade, commerce, discovery; those are his ships, bearing his merchandise, which are sailing over the sea. The card also signifies able co-operation in business, as if the successful merchant prince were looking from his side towards yours with a view to help you.The end of troubles, suspension or cessation of adversity, toil and disappointment.'},
        {name: 'Four of Wands', class: 'fourWands', img: 'images/cards/fourOfWands.jpg', def: 'They are for once almost on the surface--country life, haven of refuge, a species of domestic harvest-home, repose, concord, harmony, prosperity, peace, and the perfected work of these. Unexpected good fortune.'},
        {name: 'Five of Wands', class: 'fiveWands', img: 'images/cards/fiveOfWands.jpg', def: 'Imitation, as, for example, sham fight, but also the strenuous competition and struggle of the search after riches and fortune. In this sense it connects with the battle of life. Hence some attributions say that it is a card of gold, gain, opulence. Success in financial speculation.'},
        {name: 'Six of Wands', class: 'sixWands', img: 'images/cards/sixOfWands.jpg', def: 'The card has been so designed that it can cover several significations; on the surface, it is a victor triumphing, but it is also great news, such as might be carried in state by the King\'s courier; it is expectation crowned with its own desire, the crown of hope, and so forth.Servants may lose the confidence of their masters; a young lady may be betrayed by a friend.'},
        {name: 'Seven of Wands', class: 'sevenWands', img: 'images/cards/sevenOfWands.jpg', def: 'It is a card of valor, for, on the surface, six are attacking one, who has, however, the vantage position. On the intellectual plane, it signifies discussion, wordy strife; in business--negotiations, war of trade, barter, competition. It is further a card of success, for the combatant is on the top and his enemies may be unable to reach him.'},
        {name: 'Eight of Wands', class: 'eightWands', img: 'images/cards/eightOfWands.jpg', def: 'Activity in undertakings, the path of such activity, swiftness, as that of an express messenger; great haste, great hope, speed towards an end which promises assured felicity; generally, that which is on the move; also the arrows of love. Domestic disputes for a married person.'},
        {name: 'Nine of Wands', class: 'nineWands', img: 'images/cards/nineOfWands.jpg', def: 'The card signifies strength in opposition. If attacked, the person will meet an onslaught boldly; and his build shews, that he may prove a formidable antagonist. With this main significance there are all its possible adjuncts--delay, suspension, adjournment. Generally speaking, a bad card.'},
        {name: 'Ten of Wands', class: 'tenWands', img: 'images/cards/tenOfWands.jpg', def: 'The chief meaning is oppression simply, but it is also fortune, gain, any kind of success, and then it is the oppression of these things. It is also a card of false-seeming, disguise, perfidy. If it is a question of a lawsuit, there will be certain loss. Difficulties and contradictions, if near a good card.'},
        {name: 'Page of Wands', class: 'pageWands', img: 'images/cards/pageOfWands.jpg', def: 'Dark young man, faithful, a lover, an envoy, a postman. Beside a man, he will bear favourable testimony concerning him. A dangerous rival, if followed by the Page of Cups. Has the chief qualities of his suit. He may signify family intelligence. Young man of family in search of young lady.'},
        {name: 'Knight of Wands', class: 'knightWands', img: 'images/cards/knightOfWands.jpg', def: 'Departure, absence, flight, emigration. A dark young man, friendly. Change of residence.'},
        {name: 'Queen of Wands', class: 'queenWands', img: 'images/cards/queenOfWands.jpg', def: 'A dark woman, countrywoman, friendly, chaste, loving, honourable. If the card beside her signifies a man, she is well disposed towards him; if a woman, she is interested in the Querent. Also, love of money, or a certain success in business. A good harvest, which may be taken in several senses.'},
        {name: 'King of Wands', class: 'kingWands', img: 'images/cards/kingOfWands.jpg', def: 'Dark man, friendly, countryman, generally married, honest and conscientious. The card always signifies honesty, and may mean news concerning an unexpected heritage to fall in before very long. Generally favourable; may signify a good marriage.'},
        {name: 'The Fool', class: 'fool', img: 'images/cards/theFool.jpg', def: 'Folly, mania, extravagance, intoxication, delirium, frenzy, bewrayment.'},
        {name: 'The Magician', class: 'magician', img: 'images/cards/theMagician.jpg', def: 'Skill, diplomacy, address, subtlety; sickness, pain, loss, disaster, snares of enemies; self-confidence, will; the Querent, if male.'},
        {name: 'The High Priestess', class: 'highPriestess', img: 'images/cards/theHighPriestess.jpg', def: 'Secrets, mystery, the future as yet unrevealed; the woman who interests the Querent, if male; the Querent herself, if female; silence, tenacity; mystery, wisdom, science.'},
        {name: 'The Empress', class: 'empress', img: 'images/cards/theEmpress.jpg', def: 'Fruitfulness, action, initiative, length of days; the unknown, clandestine; also difficulty, doubt, ignorance.'},
        {name: 'The Emperor', class: 'emperor', img: 'images/cards/theEmperor.jpg', def: 'Stability, power, protection, realization; a great person; aid, reason, conviction; also authority and will.'},
        {name: 'The Priest', class: 'priest', img: 'images/cards/thePriest.jpg', def: 'Marriage, alliance, captivity, servitude; by another account, mercy and goodness; inspiration; the man to whom the Querent has recourse.'},
        {name: 'The Lovers', class: 'lovers', img: 'images/cards/theLovers.jpg', def: 'Attraction, love, beauty, trials overcome.'},
        {name: 'The Chariot', class: 'chariot', img: 'images/cards/theChariot.jpg', def: 'Succour, providence also war, triumph, presumption, vengeance, trouble.'},
        {name: 'Strength', class: 'strength', img: 'images/cards/strength.jpg', def: 'Power, energy, action, courage, magnanimity; also complete success and honours.'},
        {name: 'The Hermit', class: 'hermit', img: 'images/cards/theHermit.jpg', def: 'Prudence, circumspection; also and especially treason, dissimulation, roguery, corruption.'},
        {name: 'Wheel of Fortune', class: 'wheelOfFortune', img: 'images/cards/wheelOfFortune.jpg', def: 'Destiny, fortune, success, elevation, luck, felicity.'},
        {name: 'Justice', class: 'justice', img: 'images/cards/justice.jpg', def: 'Equity, rightness, probity, executive; triumph of the deserving side in law.'},
        {name: 'The Hanged Man', class: 'hangedMan', img: 'images/cards/theHangedMan.jpg', def: 'Wisdom, circumspection, discernment, trials, sacrifice, intuition, divination, prophecy.'},
        {name: 'Death', class: 'death', img: 'images/cards/death.jpg', def: 'End, mortality, destruction, corruption also, for a man, the loss of a benefactor for a woman, many contrarieties; for a maid, failure of marriage projects.'},
        {name: 'Temperance', class: 'temperance', img: 'images/cards/temperance.jpg', def: 'Economy, moderation, frugality, management, accommodation.'},
        {name: 'The Devil', class: 'devil', img: 'images/cards/theDevil.jpg', def: 'Ravage, violence, vehemence, extraordinary efforts, force, fatality; that which is predestined but is not for this reason evil.'},
        {name: 'The Tower', class: 'tower', img: 'images/cards/theTower.jpg', def: 'Misery, distress, indigence, adversity, calamity, disgrace, deception, ruin. It is a card in particular of unforeseen catastrophe.'},
        {name: 'The Star', class: 'star', img: 'images/cards/theStar.jpg', def: 'Loss, theft, privation, abandonment; another reading says: hope and bright prospects.'},
        {name: 'The Moon', class: 'moon', img: 'images/cards/theMoon.jpg', def: 'Hidden enemies, danger, calumny, darkness, terror, deception, occult forces, error.'},
        {name: 'The Sun', class: 'sun', img: 'images/cards/theSun.jpg', def: 'Material happiness, fortunate marriage, contentment'},
        {name: 'Judgement', class: 'judgement', img: 'images/cards/judgement.jpg', def: 'Change of position, renewal, outcome. Another account specifies total loss though lawsuit.'},
        {name: 'The World', class: 'world', img: 'images/cards/theWorld.jpg', def: 'Assured success, recompense, voyage, route, emigration, flight, change of place.'}
    ],
    positionMeanings = [
        'This card represents you in your present position. That which is the here and now as a culmination of all that has led you to this point.',
        'This card represents your present expectations; that which you believe is in your present or future. Your current and future outlook.',
        'This card represents the unexpected. That which is hidden from you, but may come to pass.',
        'This card represents your immediate future; those persons, ideas or circumstances which lie just out of reach, but are approaching and will be arriving shortly.',
        'This card represents your long-term future.'
    ],
    shuffle = function (array) {
        var currentIndex = array.length, temporaryValue, randomIndex ;

    // While there remain elements to shuffle...
        while (0 !== currentIndex) {

    // Pick a remaining element...
            randomIndex = Math.floor(Math.random() * currentIndex);
            currentIndex -= 1;

    // And swap it with the current element.
            temporaryValue = array[currentIndex];
            array[currentIndex] = array[randomIndex];
            array[randomIndex] = temporaryValue;
        }

        return array;
    };

$(function () {

    
});